### ISSUE TITLE
Problem im Zusammenspiel mit Rocksolid Slider

### ISSUE THREAD

**Issue by mlwebworker** [may17/contao-quickArticleSwitch#2]
Verwendet wird ein Rocksolid Slider vom Typ Inhalts-Slider
Versucht man die einzelnen Inhaltselemente zu bearbeiten erscheint folgende Fehlermeldung.
Eine Bearbeitung ist also nicht möglich.

`Fatal error: Uncaught exception Error with message Call to a member function count() on null thrown in system\modules\quickArticleSwitch\classes\backend\ArticleSwitch.php on line 13

#0 system\modules\core\classes\DataContainer.php(785): May17\quickArticleSwitch\Classes\Backend\ArticleSwitch->addSwitch(NULL, 'quickArticleSwi...', 'quickArticleSwi...', NULL, '', 'tl_content', NULL)
#1 system\modules\core\drivers\DC_Table.php(3882): Contao\DataContainer->generateGlobalButtons()
#2 system\modules\core\drivers\DC_Table.php(378): Contao\DC_Table->parentView()
#3 system\modules\core\classes\Backend.php(650): Contao\DC_Table->showAll()
#4 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('rocksolid_slide...')
#5 contao\main.php(20): Contao\BackendMain->run()
#6 {main}
`
Contao 3.5.24, be-quickArticleSwitch 1.1.0
Wird die Erweiterung deaktiviert ist der Fehler weg.

**Comment by mlwebworker** [comment]
``

**Comment by may17** [comment]
War der close des tickets beabsichtigt von dir?

**Comment by mlwebworker** [comment]
Nein war versehentlich,

**Comment by mlwebworker** [comment]
Wie krieg ich den wieder auf? Bin da noch nicht so firm auf Github. #

**Comment by may17** [comment]
Ich wollte mir mal das Problem ansehen. Ich kenne den Rocksolid Slider aber nicht und bräuchte da ein paar weitere Informationen von dir. Hast du ein paar Informationen was ich einstellen muss? Betrifft das die Pro Version?

**Comment by may17** [comment]
Ah ok, ich sehe wo das Problem liegt und zwar wird der Article Switch bei allen Content Elementen angezeigt. Die Funktion sollte aber nur bei den Artikeln zu Verfügung stehen.

Ich spiele mal ein Patch ein. Gerne kannst du dann testen ob der Fehler immer noch besteht.

**Comment by may17** [comment]
So ich habe nen bugfix release on gestellt. Magst du mal schauen ob der Fehler immer noch auftritt?

**Comment by mlwebworker** [comment]
Fehler ist weg. Danke.
War bei mir im übrigen die ganz normale kostenlos verfügbare Version des Sliders. Sollte aber m.E. egal sein.

**Comment by may17** [comment]
Danke dir für das Feedback. In diesem Fall spielte es tatsächlich keine Rolle da alle Contao Module betroffen waren die Content Elemente nutzen (bis auf Artikel). Das betraf auch die News / Events etc.

Schön das der Fehler nun beseitigt ist.
